online_movie/movie_app/urls.py
from . import views
from django.urls import path

app_name = 'movie_app'
urlpatterns = [
    path('', views.display, name='display'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

online_movie/online_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from online_movie import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

online_movie/movie_app/models.py
from django.db import models


class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

online_movie/movie_app/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

online_movie/movie_app/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


def display(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
               }
    return render(request, 'index.html', context)


def details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

online_movie/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  FILM_NAME<input type="text" name="name" placeholder="ENTER FILM'S NAME"><br><br>
  DESCRIPTION<input type="text" name="desc" placeholder="ENTER FILM'S DESCRIPTION"><br><br>
  YEAR<input type="number" name="year" placeholder="ENTER FILM'S YEAR"><br><br>
  IMAGE<input type="file" name="img" placeholder="ENTER FILM'S IMAGE"><br><br>
  <input type="submit" value="SUBMIT"><br>
</form>

{% endblock %}

online_movie/templates/add_films.html
{% extends 'base.html' %}
{% block body %}

<form method="post">
  {% csrf_token %}
  <center>
  <h4>ADD MOVIES HERE</h4>
  <br>
  <a class="btn btn-outline-warning" href="{% url 'movie_app:display' %}">>SUBMIT</a>
  </center>
</form>

{% endblock %}

online_movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>INDEX</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<body>
<!--BOOTSTRAP TOUCH UP-->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      ONLINE MOVIE STORE
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

online_movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="post">
  {% csrf_token %}
  <h4>ARE YOU WANT TO DELETE THIS MOVIE ?</h4>
  <input type="submit" value="SUBMIT">
</form>

{% endblock %}

online_movie/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h4>{{movie.desc}}</h4>
            <h5>{{movie.year}}</h5>
            <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">UPDATE</a>
            <a class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">DELETE</a>
        </div>
    </div>
</div>
{% endblock %}

online_movie/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="SUBMIT">
</form>
{% endblock %}

online_movie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">


{% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
                <img src="{{i.img.url}}" class="card-img-top" height="250" >
                <div class="card-body">
                    <h4 class="card-title">{{i.name}}</h4>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movie_app:details' i.id %}"><h3>ABOUT {{i.name}}</h3></a>
                </div>
            </div>
        </div>
<!--URL SETTING-->
<!--NAME SPACE-->
{% endfor %}
{% endblock %}
    </div>
</div>